#Персонажи
define me = Character('Я', color="#6bbcff")
define bunny_queen_unknown = Character('Незнакомка', color="#ff6ddf")
define bunny_queen = Character('Ева-зайка', color="#ff6ddf")
define rita = Character('Рита', color="#ff3c3c")
define unknown_crab_girl = Character('Крабоженщина', color="#ff3c3c")
define conductor = Character('Проводник', color="#08af48")
define evangelina_noname = Character('Незнакомка', color="#08af48")
define evangelina = Character('Евангелина', color="#08af48")
define petr_unknown = Character('Граф', color="#810a0a")
define petr = Character('Граф Петр', color="#810a0a")
define varvara_noname = Character('Незнакомка', color="#3280da")
define varvara = Character('Варвара', color="#3280da")
define annushka_noname = Character('Незнакомка', color="#e7437a")
define annushka = Character('Аннушка', color="#e7437a")
define bandit_one = Character('Бандит 1', color="#20030d")
define bandit_two = Character('Бандит 2', color="#20030d")