#Фоны
image dream_forest = "images/backgrounds/dream_forest.jpg"
image character_room = "images/backgrounds/character_room.png"
image igor_rita = "images/backgrounds/igor_rita.png"
image train = "images/backgrounds/train.png"
image empire_train = "images/backgrounds/empire_train.png"
image girl_train = "images/backgrounds/girl_train.png"
image train_station_past = "images/backgrounds/train_station_past.jpg"
image empire_city = "images/backgrounds/empire_city.jpg"
image igor_scary = "images/backgrounds/igor_scary.png"
image empire_city_second = "images/backgrounds/empire_city_second.png"
image atlantic_city = "images/backgrounds/atlantic_city.png"

#Персонажи
image BunnyQueenUnknown = "images/characters/bunny_queen.png"
image Conductor = "images/characters/conductor.png"
image Evangelina = "images/characters/evangelina.png"
image CrabQueen = "images/characters/crab_queen.png"
image GrafPetr = "images/characters/petr.png"
image Varvara = "images/characters/varvara.png"